spring.application.name=bfriend

# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-consoleb
spring.datasource.url=jdbc:h2:~/localb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=suyeon
spring.datasource.password=
# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
